### ISSUE TITLE
Using for UnitTests (not Selenium/GUI)

### ISSUE THREAD

**Issue by enigmab17** [sscobici/ParallelTestRunner#3]
Hey

Just wondering, couldn't find a more suitable place to ask you this, however got a surprising timing issue when using it to just run unit tests.
Any thoughts/ideas?

Test Project Details:
Number of Test Assemblies: 12
Total number of tests in those Assemblies: 118

Running the below command:
C:\BuildTools\CommandLine\ParallelTestRunner\ParallelTestRunner.exe provider:VSTEST_2015 root:"C:\TestResults\Temp" threadcount:8 plevel:TestMethod out:c:\TestResults\TestResults.trx <List of DLL's here>

It successfully kicks off and runs the tests, but the total duration is quite a bit longer than doing directly through VS.

Averages:
Run tests locally through VS2015 using dotCover: < 10 seconds
Run tests on build server: <30 seconds
Run tests through ParallelTestRunner: 40-50 seconds

I appreciate you might not have designed it to actually benefit unit tests, but can't see any information on it so just checking if there was something I was doing wrong?

Many thanks :)

**Comment by sscobici** [comment]
Hi,

This is not designed for running short tests - cause the cost of starting
up new thread is too high. This is for Long running UI tests  > 1h

For running the unittests in parallel there is an option in test settings
config file, don't remember how it is called.

Regards,

**Comment by enigmab17** [comment]
Figured as much :)
Just thought I would ask.

Yea I've got the parallel unit tests running in MSTest, but that does it on the container level of an assembly, so was looking to see if this would help running them quicker.

Thanks for the assist anyway.
